### ISSUE TITLE
Username and Password Input Field Labels Malformed

### ISSUE THREAD

**Issue by N3rdP1um23** [djtimca/haomnilogic#11]
After coming across the information for the HACS integration (YAY!! Just in time for the new season!), I've gone ahead and set it up and all worked okay!

I didn't initially see a way to change the pump speed so I figured a clean install would help (I just came across #9 which I'll look into now haha). That being said, as I was setting up the new integration, I noticed that, when asked to enter the credentials, the input labels aren't properly formatted. Just though I'd raise an issue in case it's something that can be adjusted (unless it's out of your hands). I see the following for the username and password fields. A hard refresh of the page to clear the browser cache doesn't correct the issue

![image](https://user-images.githubusercontent.com/8093806/172234352-0e219ae4-eac4-4e74-adf2-f99e80335170.png)

Once again, thank you so much for the work on this integration!! The transition and new abilities are amazing, and I can't wait to dig into it!! 😃

**Comment by djtimca** [comment]
Thanks - this appears to be related to translations in Home Assistant. Can anyone else confirm this same behaviour on another implementation.

**Comment by sddgit** [comment]
I got the same thing. I uninstalled the integration and the HACS integration. At the next install, I made sure to restart HA after the HACS install, before doing the HA integration install, and it went away.

Something else puzzles me now. When I go to Settings/Integrations, find the Omnilogic integration, then select Configure, I get this.

![23F1883F-DBF7-4480-8941-C4B75C6237F1](https://user-images.githubusercontent.com/76281052/172505076-1ce621c9-8b4b-4700-8502-ca12e832772b.jpeg)

I don’t know what the second field is, and I was expecting to see the username and password fields included.

**Comment by djtimca** [comment]
I have to update some translation strings tomorrow for this to pop up. 

Username and password aren't available except during setup which is standard for HA integrations. If you need to change username or password you need to remove and reinstall the integration.

**Comment by sddgit** [comment]
Thanks. What’s the second, unlabelled field for?

**Comment by djtimca** [comment]
I believe it is the offset for the ORP sensor in case it doesn't match the app. Will have a label in the next release either way.

**Comment by sddgit** [comment]
Thanks.

**Comment by djtimca** [comment]
Fixed in today's release (for both).
