### ISSUE TITLE
Cannot toggle a Switch which isn't associated with a BoW

### ISSUE THREAD

**Issue by lurgh** [djtimca/haomnilogic#20]
I can't control lights/switches that are not associated with a Body of Water in Omnilogic.  I have a patch for this which I have been using for months with old switch.py code to work around the issue and it continues to work for me in this release.

I opened a PR to share the patch that works for me, for your reference, but it may not be optimal.

My telemetry file is attached.

[telemetry.json.txt](https://github.com/djtimca/haomnilogic/files/8884445/telemetry.json.txt)

**Comment by lurgh** [comment]
PR submitted for your reference, #19

**Comment by djtimca** [comment]
Merged. Thanks for your support!
