### ISSUE TITLE
ColorLogic Lights Not Showing as Devices

### ISSUE THREAD

**Issue by TMarzullo** [djtimca/haomnilogic#21]
I don't know if I should put this here first, or try to post in the community, so let me know if I should start there because I don't know if  this is an issue for anyone else, but my Pool Lights do not show up at all. I guess I need to know if the lights will show up automatically after installation or if there is some additional step I am missing. I have also done the required reboot multiple times as I troubleshoot (getting my instance of HA up to the current release and such). I was previously utilizing the Hayward OmniLogic integration, but from what I have read in in the[ community discussions ](https://community.home-assistant.io/t/hayward-omnilogic/122522/151)that shouldn't be a problem as this just overides the built in integration.

I am running:
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

And I just installed the updated custom integration from HACS to 1.0.13 but it doesn't seem to fix my issue. I have tried deleting the reinstalling the built in integration but everything I have tried only gets me the entities for the Air Temp, Water Temp, and Filter Pump, the Filter Pump Alarm and the Filter Pump Speed. I have attached my telemetry data and response data from the Replit testing harness. I am hoping I am just missing some step and I can beg your forgiveness for wasting your time. Any help is appreciated.

Telemetry:
`[{
        'systemId': 'REDACTED',
        'statusVersion': '5',
        'airTemp': '81',
        'status': '1',
        'state': '1',
        'configUpdatedTime': '0001-01-01T00:00:00',
        'datetime': '2022-06-14T16:34:07.2894091',
        'Relays': [],
        'BOWS': [{
                'systemId': '1',
                'flow': '255',
                'waterTemp': '87',
                'Name': 'Pool',
                'Supports-Spillover': 'no',
                'Filter': {
                    'systemId': '2',
                    'valvePosition': '1',
                    'filterSpeed': '60',
                    'filterState': '1',
                    'lastSpeed': '18',
                    'Name': 'Filter Pump',
                    'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED',
                    'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP',
                    'Max-Pump-Speed': '100',
                    'Min-Pump-Speed': '18',
                    'Max-Pump-RPM': '3450',
                    'Min-Pump-RPM': '600',
                    'Priming-Enabled': 'yes',
                    'Alarms': []
                },
                'VirtualHeater': {
                    'systemId': '0',
                    'Current-Set-Point': '0',
                    'enable': 'no'
                },
                'CSAD': {
                    'systemId': '0',
                    'ph': '',
                    'orp': '',
                    'status': '0',
                    'mode': '0',
                    'Alarms': []
                },
                'Group': {
                    'systemId': '17',
                    'groupState': '0'
                },
                'Lights': [{
                        'systemId': '5',
                        'lightState': '0',
                        'currentShow': '12',
                        'speed': '3',
                        'brightness': '4'
                    }
                ],
                'Relays': [],
                'Pumps': [],
                'Heaters': []
            }
        ],
        'BackyardName': 'REDACTED',
        'Msp-Vsp-Speed-Format': 'RPM',
        'Msp-Time-Format': '12 Hour Format',
        'Units': 'Standard',
        'Msp-Chlor-Display': 'Salt',
        'Msp-Language': 'English',
        'Unit-of-Measurement': 'Standard',
        'Alarms': [],
        'Unit-of-Temperature': 'UNITS_FAHRENHEIT'
    }
]
`

Response Data:
`<Response>
	<MSPConfig>
		<System>
			<Msp-Vsp-Speed-Format>RPM</Msp-Vsp-Speed-Format>
			<Msp-Time-Format>12 Hour Format</Msp-Time-Format>
			<Units>Standard</Units>
			<Msp-Chlor-Display>Salt</Msp-Chlor-Display>
			<Msp-Language>English</Msp-Language>
			<UI-Display-Mode>standard</UI-Display-Mode>
			<UI-MoodColor-Enabled>Yes</UI-MoodColor-Enabled>
			<UI-Heater-SimpleMode>Yes</UI-Heater-SimpleMode>
			<UI-Filter-SimpleMode>Yes</UI-Filter-SimpleMode>
			<UI-Lights-SimpleMode>Yes</UI-Lights-SimpleMode>
		</System>
		<Backyard>
        MSP Configuration
        <System-Id>0</System-Id>
			<Name>Backyard</Name>
			<Service-Mode-Timeout>0</Service-Mode-Timeout>
			<Sensor>
				<System-Id>3</System-Id>
				<Name>AirSensor</Name>
				<Type>SENSOR_AIR_TEMP</Type>
				<Units>UNITS_FAHRENHEIT</Units>
			</Sensor>
			<ColorLogic-Light>
				<System-Id>5</System-Id>
				<Name>Pool Lights</Name>
				<Type>COLOR_LOGIC_UCL</Type>
				<V2-Active>yes</V2-Active>
			</ColorLogic-Light>
			<Body-of-water>
            01
            <System-Id>1</System-Id>
				<Name>Pool</Name>
				<Type>BOW_POOL</Type>
				<Shared-Type>BOW_NO_EQUIPMENT_SHARED</Shared-Type>
				<Shared-Priority>SHARED_EQUIPMENT_LOW_PRIORITY</Shared-Priority>
				<Shared-Equipment-System-ID>0</Shared-Equipment-System-ID>
				<Supports-Spillover>no</Supports-Spillover>
				<Size-In-Gallons>7500</Size-In-Gallons>
				<Filter>
					<System-Id>2</System-Id>
					<Name>Filter Pump</Name>
					<Shared-Type>BOW_NO_EQUIPMENT_SHARED</Shared-Type>
					<Filter-Type>FMT_VARIABLE_SPEED_PUMP</Filter-Type>
					<Max-Pump-Speed>100</Max-Pump-Speed>
					<Min-Pump-Speed>18</Min-Pump-Speed>
					<Max-Pump-RPM>3450</Max-Pump-RPM>
					<Min-Pump-RPM>600</Min-Pump-RPM>
					<Priming-Enabled>yes</Priming-Enabled>
					<Vsp-Low-Pump-Speed>18</Vsp-Low-Pump-Speed>
					<Vsp-Medium-Pump-Speed>50</Vsp-Medium-Pump-Speed>
					<Vsp-High-Pump-Speed>100</Vsp-High-Pump-Speed>
					<Vsp-Custom-Pump-Speed>100</Vsp-Custom-Pump-Speed>
					<Freeze-Protect-Override-Interval>7200</Freeze-Protect-Override-Interval>
				</Filter>
				<Sensor>
					<System-Id>4</System-Id>
					<Name>WaterSensor</Name>
					<Type>SENSOR_WATER_TEMP</Type>
					<Units>UNITS_FAHRENHEIT</Units>
				</Sensor>
			</Body-of-water>
		</Backyard>
		<Schedules>
			<sche>
				<bow-system-id>1</bow-system-id>
				<equipment-id>2</equipment-id>
				<schedule-system-id>7</schedule-system-id>
				<event>164</event>
				<data>60</data>
				<enabled>1</enabled>
				<start-minute>0</start-minute>
				<start-hour>7</start-hour>
				<end-minute>0</end-minute>
				<end-hour>19</end-hour>
				<days-active>127</days-active>
				<recurring>1</recurring>
			</sche>
			<sche>
				<bow-system-id>1</bow-system-id>
				<equipment-id>2</equipment-id>
				<schedule-system-id>8</schedule-system-id>
				<event>164</event>
				<data>47</data>
				<enabled>1</enabled>
				<start-minute>0</start-minute>
				<start-hour>19</start-hour>
				<end-minute>0</end-minute>
				<end-hour>7</end-hour>
				<days-active>127</days-active>
				<recurring>1</recurring>
			</sche>
			<sche>
				<bow-system-id>0</bow-system-id>
				<equipment-id>5</equipment-id>
				<schedule-system-id>9</schedule-system-id>
				<event>164</event>
				<data>262924</data>
				<enabled>1</enabled>
				<start-minute>14</start-minute>
				<start-hour>18</start-hour>
				<end-minute>0</end-minute>
				<end-hour>0</end-hour>
				<days-active>127</days-active>
				<recurring>1</recurring>
			</sche>
			<sche>
				<bow-system-id>0</bow-system-id>
				<equipment-id>17</equipment-id>
				<schedule-system-id>19</schedule-system-id>
				<event>317</event>
				<data>1</data>
				<enabled>1</enabled>
				<start-minute>8</start-minute>
				<start-hour>18</start-hour>
				<end-minute>0</end-minute>
				<end-hour>0</end-hour>
				<days-active>127</days-active>
				<recurring>1</recurring>
			</sche>
			<sche>
				<bow-system-id>0</bow-system-id>
				<equipment-id>17</equipment-id>
				<schedule-system-id>20</schedule-system-id>
				<event>317</event>
				<data>1</data>
				<enabled>1</enabled>
				<start-minute>52</start-minute>
				<start-hour>16</start-hour>
				<end-minute>0</end-minute>
				<end-hour>0</end-hour>
				<days-active>127</days-active>
				<recurring>1</recurring>
			</sche>
		</Schedules>
		<Favorites>
			<Favorite>
				<System-Id>10</System-Id>
				<Index-Id>1</Index-Id>
				<EquipmentID-Or-ThemeID>5</EquipmentID-Or-ThemeID>
				<Sequence>0</Sequence>
				<Data>0</Data>
				<Data2>4</Data2>
				<Data3>4</Data3>
				<SimpleModeEnabled>1</SimpleModeEnabled>
			</Favorite>
			<Favorite>
				<System-Id>15</System-Id>
				<Index-Id>3</Index-Id>
				<EquipmentID-Or-ThemeID>14</EquipmentID-Or-ThemeID>
				<Sequence>2</Sequence>
				<Data>268435455</Data>
				<SimpleModeEnabled>1</SimpleModeEnabled>
			</Favorite>
			<Favorite>
				<System-Id>16</System-Id>
				<Index-Id>4</Index-Id>
				<EquipmentID-Or-ThemeID>5</EquipmentID-Or-ThemeID>
				<Sequence>3</Sequence>
				<Data>12</Data>
				<Data2>3</Data2>
				<Data3>4</Data3>
				<SimpleModeEnabled>1</SimpleModeEnabled>
			</Favorite>
			<Favorite>
				<System-Id>18</System-Id>
				<Index-Id>5</Index-Id>
				<EquipmentID-Or-ThemeID>17</EquipmentID-Or-ThemeID>
				<Sequence>4</Sequence>
				<Data>268435455</Data>
				<SimpleModeEnabled>1</SimpleModeEnabled>
			</Favorite>
		</Favorites>
		<Groups>
			<Group>
				<System-Id>14</System-Id>
				<Name>VoodooLounge</Name>
				<Icon-Id>14</Icon-Id>
				<Request>
					<Name>TurnOnOffForGroup</Name>
					<Parameters>
						<Parameter name="PoolID" dataType="int">0</Parameter>
						<Parameter name="EquipmentID" dataType="int">5</Parameter>
						<Parameter name="Data" dataType="int">263168</Parameter>
						<Parameter name="LightState" dataType="int">1</Parameter>
					</Parameters>
				</Request>
				<Request>
					<Name>TurnOnOffForGroup</Name>
					<Parameters>
						<Parameter name="PoolID" dataType="int">1</Parameter>
						<Parameter name="EquipmentID" dataType="int">2</Parameter>
						<Parameter name="Data" dataType="int">76</Parameter>
						<Parameter name="LightState" dataType="int">0</Parameter>
					</Parameters>
				</Request>
			</Group>
			<Group>
				<System-Id>17</System-Id>
				<Name>Evening</Name>
				<Icon-Id>17</Icon-Id>
				<Request>
					<Name>TurnOnOffForGroup</Name>
					<Parameters>
						<Parameter name="PoolID" dataType="int">0</Parameter>
						<Parameter name="EquipmentID" dataType="int">5</Parameter>
						<Parameter name="Data" dataType="int">262924</Parameter>
						<Parameter name="LightState" dataType="int">1</Parameter>
					</Parameters>
				</Request>
				<Request>
					<Name>TurnOnOffForGroup</Name>
					<Parameters>
						<Parameter name="PoolID" dataType="int">1</Parameter>
						<Parameter name="EquipmentID" dataType="int">2</Parameter>
						<Parameter name="Data" dataType="int">57</Parameter>
						<Parameter name="LightState" dataType="int">0</Parameter>
					</Parameters>
				</Request>
			</Group>
		</Groups>
	</MSPConfig>
	<MSPAPI version="0.4" latestversion="0.4">
		<Device-APIs>
			<API System-Id="5" OpType="ON_OFF" ref="SetUIEquipmentCmd" EquipmentID="5" IsOn="API::STATUS::ColorLogic-Light::lightState"/>
			<API System-Id="5" OpType="ON_SETPOINT" ref="SetStandAloneLightShowV2" LightID="5" Show="API::STATUS::ColorLogic-Light::currentShow" Speed="API::STATUS::ColorLogic-Light::speed" Brightness="API::STATUS::ColorLogic-Light::brightness"/>
			<API System-Id="14" OpType="ON_OFF" ref="RunGroupCmd" ThemeID="14" IsOn="API::STATUS::Group::groupState"/>
			<API System-Id="17" OpType="ON_OFF" ref="RunGroupCmd" ThemeID="17" IsOn="API::STATUS::Group::groupState"/>
			<API System-Id="2" OpType="ON_OFF" ref="SetUIEquipmentCmd" EquipmentID="2" IsOn="API::STATUS::Filter::filterSpeed"/>
			<API System-Id="0" OpType="ON_OFF" ref="SetHeaterEnable" HeaterID="0"/>
			<API System-Id="0" OpType="SETPOINT" ref="SetUIHeaterCmd" HeaterID="0" Temp="API::STATUS::VirtualHeater::Current-Set-Point"/>
			<API System-Id="0" OpType="CSAD_MODE" ref="UISetCSADMode" CSADID="0" Mode="API::STATUS::CSAD::mode"/>
			<API System-Id="0" OpType="CSAD_CALIBRATION" ref="UISetCSADTargetValue" CSADID="0" Mode="API::STATUS::CSAD::ph"/>
		</Device-APIs>
		<Favorite-APIs>
			<API Favorite-Id="5" ref="SetStandAloneLightShowV2" OpType="ON_SETPOINT" LightID="5" Show="API::CONFIG::Favorite::Data" Speed="API::CONFIG::Favorite::Data2" Brightness="API::CONFIG::Favorite::Data3"/>
			<API Favorite-Id="14" ref="RunGroupCmd" OpType="ON_OFF" ThemeID="14" IsOn="API::STATUS::Group::groupState"/>
			<API Favorite-Id="17" ref="RunGroupCmd" OpType="ON_OFF" ThemeID="17" IsOn="API::STATUS::Group::groupState"/>
			<API Favorite-Id="2" ref="SetUIEquipmentCmd" OpType="ON_OFF" EquipmentID="2" IsOn="API::STATUS::Filter::filterState"/>
			<API Favorite-Id="0" ref="API::GOTOFEATURE"/>
			<API Favorite-Id="1" ref="SetHeaterEnable" HeaterID="0"/>
			<API Favorite-Id="0" ref="API::GOTOFEATURE"/>
		</Favorite-APIs>
		<Schedule-APIs>
			<API System-Id="5" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleAltCmd" EquipmentID="5" Show="API::STATUS::ColorLogic-Light::currentShow" Speed="API::STATUS::ColorLogic-Light::speed" Brightness="API::STATUS::ColorLogic-Light::brightness" Data4="0" ActionID="308"/>
			<API System-Id="5" OpType="EDIT_SCHEDULE" ref="EditUIScheduleAltCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Show="API::STATUS::ColorLogic-Light::currentShow" Speed="API::STATUS::ColorLogic-Light::speed" Brightness="API::STATUS::ColorLogic-Light::brightness" Data4="0" ActionID="308"/>
			<API System-Id="5" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id"/>
			<API System-Id="14" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="14" Data="1" ActionID="317"/>
			<API System-Id="14" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="1" ActionID="317"/>
			<API System-Id="14" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id"/>
			<API System-Id="17" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="17" Data="1" ActionID="317"/>
			<API System-Id="17" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="1" ActionID="317"/>
			<API System-Id="17" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id"/>
			<API System-Id="2" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="2" Data="API::STATUS::Filter::filterSpeed" ActionID="164"/>
			<API System-Id="2" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="API::STATUS::Filter::filterSpeed" ActionID="164"/>
			<API System-Id="2" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id"/>
			<API System-Id="0" OpType="CREATE_SCHEDULE" ref="CreateUIScheduleCmd" EquipmentID="0" Data="API::STATUS::VirtualHeater::Current-Set-Point" ActionID="315"/>
			<API System-Id="0" OpType="EDIT_SCHEDULE" ref="EditUIScheduleCmd" EquipmentID="API::CONFIG::sche::schedule-system-id" Data="API::STATUS::VirtualHeater::Current-Set-Point" ActionID="315"/>
			<API System-Id="0" OpType="REMOVE_SCHEDULE" ref="DeleteUIScheduleCmd" ScheduleSystemID="API::CONFIG::sche::schedule-system-id"/>
		</Schedule-APIs>
	</MSPAPI>
</Response>`

**Comment by djtimca** [comment]
@TMarzullo thanks for posting and including all the telemetry etc! Looking at things for some reason the flag that your lights are version 2 didn't come through. I've made a change to the Replit to test before I push an update to the integration. Can you re-run and post your telemetry file again? MSP config is optional this time. Thanks!

**Comment by TMarzullo** [comment]
Tim,

Thank you so much for taking a look. I really appreciate it. I reran the telemetry as requested. See below:

`[{'systemId': 'REDACTED', 'statusVersion': '5', 'airTemp': '80', 'status': '1', 'state': '1', 'configUpdatedTime': '0001-01-01T00:00:00-06:00', 'datetime': '2022-06-15T08:17:36.0584', 'Relays': [], 'BOWS': [{'systemId': '1', 'flow': '255', 'waterTemp': '84', 'Name': 'Pool', 'Supports-Spillover': 'no', 'Filter': {'systemId': '2', 'valvePosition': '1', 'filterSpeed': '60', 'filterState': '1', 'lastSpeed': '18', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_NO_EQUIPMENT_SHARED', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '18', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'yes', 'Alarms': []}, 'VirtualHeater': {'systemId': '0', 'Current-Set-Point': '0', 'enable': 'no'}, 'CSAD': {'systemId': '0', 'ph': '', 'orp': '', 'status': '0', 'mode': '0', 'Alarms': []}, 'Group': {'systemId': '17', 'groupState': '0'}, 'Lights': [{'systemId': '5', 'lightState': '0', 'currentShow': '12', 'speed': '3', 'brightness': '4'}], 'Relays': [], 'Pumps': [], 'Heaters': []}], 'BackyardName': 'REDACTED', 'Msp-Vsp-Speed-Format': 'RPM', 'Msp-Time-Format': '12 Hour Format', 'Units': 'Standard', 'Msp-Chlor-Display': 'Salt', 'Msp-Language': 'English', 'Unit-of-Measurement': 'Standard', 'Alarms': [], 'Unit-of-Temperature': 'UNITS_FAHRENHEIT'}]`

**Comment by djtimca** [comment]
Actually I think I may have found the issue and have included it in this morning's release. Please do an update @TMarzullo from HACS and if the lights show up properly now please close this issue. If not, I'll need to do more digging.

**Comment by TMarzullo** [comment]
Hi Tim,
Sorry for the delayed response. I pulled the new version and installed it and a new light entity did indeed show up (yay!).
Note: My pool has two lights that are configured as a single light so that they are synchronized which is why there is only one entity (I am assuming)

There still seems to be an issue with actually controlling them. If I turn them on, I see the entry in the Logbook that says:

> "Pool Light turned on triggered by service light.turn_on"

But within a minute the state changes to off with an entry in the logbook of:

> "Pool Light turned off"

I configured a custom light card for the new entity, but it too is unable to change anything. I does seem to be able to read some state values.  -for example if I manually turn them on, it will be reflected accurately in the entity as will the Effect that is currently enabled.

What additional data can I collect from my setup that could assist you? I have no problem letting my setup be a testing ground for anything you need.

Additional Notes: I would imagine that your custom integration is limited to functionality that Hayward exposes to me through my control panel/app. If this is correct, then we shouldn't expect color wheel functionality because solid, fixed colors are only available as predefined values and can not be configured beyond brightness (Hayward seems to have a really underwhelming driver). So I would imagine that the effects via the drop down, the brightness, the on/off state and speed are probably the only options for control. This is really more of an FYI but I thought it might be useful information. At the very least I wanted to tell you how grateful I am for everything you have already done.

**Comment by TMarzullo** [comment]
Pool Hardware companies are all bizarre I am coming to realize :)

I will double check on the brightness and speed values with the custom service but in the meantime I took a look at the Home Assistant Core logs after trying to turn on the lights. While I didn't see any entries that specifically said Hayward, Omni, or Pool...there is a Python error that is within a minute of the attempt. 

`Logger: pynetgear.router
Source: /usr/local/lib/python3.9/site-packages/pynetgear/router.py:405
First occurred: 1:54:59 PM (31 occurrences)
Last logged: 2:35:07 PM

login using all known port-ssl combinations failed.`

Could that be the issue?

**Comment by djtimca** [comment]
Should be fixed in latest release.
