### ISSUE TITLE
Are Hayward themes supported in the API?

### ISSUE THREAD

**Issue by sddgit** [djtimca/haomnilogic#26]
Hayward has a “themes” feature, whereby you can group devices etc. and control them as a single entity. Is there any support for these in the API? I realise I could duplicate this functionality in HA itself, but just wondering….

**Comment by djtimca** [comment]
Unfortunately not something that is available on the API. I moved all my themes to HA as soon as I could manage everything there.

**Comment by sddgit** [comment]
OK, thanks for letting me know so quickly.
