### ISSUE TITLE
Error durring initial startup having to do with Backyard

### ISSUE THREAD

**Issue by rukiddin** [djtimca/haomnilogic#27]
Just installed Home Assistant Core yesterday, running version 2022.6.7.

Added the Omnilogic device, not sure how to tell the version on it, but it installed yesterday.

Here's the error I'm getting:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/omnilogic/__init__.py", line 41, in async_setup_entry
    await api.get_telemetry_data()
  File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 1023, in get_telemetry_data
    if type(config_item["Backyard"]["Sensor"]) == dict:
KeyError: 'Sensor'`

Here's the output I got using your debugging tool

`Saved file: output_116_9ac0875443_mspconfig.xml
Saved file: output_116_9c26ae8f1d_telemetry.xml
An error occurred: list indices must be integers or slices, not str
Press enter to clear.`

Some additional info:  the pool has a spa and LED color lights.  It also has a breaker that controls an outlet which powers backyard lights.  That’s the “backyard” switch.

**Comment by djtimca** [comment]
Have you installed the version from HACS or are you trying to run the version in the Home Assistant core? 

Based on the error message it looks to me like the core version which we aren't supporting here. Please follow the instructions to install via HACS on the main page of this repo.

The info from the debugging tool is interesting, but until you install the HACS version it's not likely helpful.
