### ISSUE TITLE
Heater issues when exposed to Homekit through Home Assistant

### ISSUE THREAD

**Issue by edrikk** [djtimca/haomnilogic#28]
When exposing the pool water heater to homekit, I found that the heater began acting very strange and would not stay on (it would become disabled in the Omnilogic App).

Checking the Home Assistant logs I see the below error message:

`[31m2022-07-03 22:30:38 ERROR (MainThread) [pyhap.characteristic] TargetHeatingCoolingState: value=0 is an invalid value.`

This [old homebridge ticket](https://github.com/homebridge/homebridge/issues/2960) seems to concur that the value 0 means "Off" which would line up with the behavior that I saw.

Also found[ this HA "fix/workaround"](https://github.com/home-assistant/core/pull/60220) that I wanted to flag...

Sharing this in case there is a property that isn't being set correctly in haomnilogic.

**Comment by djtimca** [comment]
This appears to be related to HomeKit not this integration unfortunately. We are using the standard Home Assistant values for `STATE_ON` and `STATE_OFF` as well as their in-built values for `SUPPORT_OPERATION_MODE` and `SUPPORT_TARGET_TEMPERATURE`

`STATE_ON` in Home Assistant is defined in their const.py as 'on'
`STATE_OFF` in Home Assistant is defined as 'off'

If HomeKit is sending `0` it would be interpreted as invalid before it gets to this integration. 

Unfortunately not something I can fix here.
