### ISSUE TITLE
Globrite color changing

### ISSUE THREAD

**Issue by jmbinette** [djtimca/haomnilogic#31]
Hi, Thank you for this integration !

Anyone explored the idea of automating color change on a regular GLOBRITE light ?
You have to cycle power on the light to obtain various modes.

They do sell a module for this specifically but quite expensive ! 
https://www.pentair.com/en-us/products/residential/pool-spa-equipment/pool-lighting/intellibrite_controller.html

Any way to automate this in HA ?

`**Number of times to cycle power (1-14)**`
`1 SAm Mode: Cycles through white, magenta, blue and green colors 
(emulates the Pentair SAm® color changing light).

2 Party Mode: Rapid color changing building energy and excitement.

3 Romance Mode: Slow color transitions creating a mesmerizing and 
calming effect.

4 Caribbean Mode: Transitions between a variety of blues and greens.

5 American Mode: Patriotic red, white and blue transition.

6 California Sunset Mode: Dramatic transitions of orange, red and 
magenta tones.

7 Royal Mode: Richer, deeper color tones. 

8 Blue: Fixed color.

9 Green: Fixed color.

10 Red: Fixed color.

11 White: Fixed color.

12 Magenta: Fixed color.

13 Hold: Save the current color effect during a color light show.

14 Recall: Activate the last saved color effect.`

**Comment by djtimca** [comment]
How does the light appear in your Hayward system? Can you run the diagnostics and post the files from your system so we can have a look? 

I believe you'll likely still need the controller but not sure - I'm not sure I would want to try to do a timed power cycle through the cloud API.

**Comment by jmbinette** [comment]
It appears as a switch, not a light

The controller basically "blinks" a relay x times to change effect.

I understand your point about switching using the API.

What if I install a smart switch before my lights and we "blink" this
switch ?

**Comment by djtimca** [comment]
You could try something like a smart switch with a local API. 

With the existing integration you could try an automation from HA to trigger the switch on/off to see how it works from the cloud. 

My hunch is that it might work just will be unreliable from network latency etc.

**Comment by jmbinette** [comment]
Maybe a custom firmware on ESPhome with custom function (ie.
Count,duration,delay)

What do you think ?

**Comment by djtimca** [comment]
That's actually a great idea - likely an ESP based relay would be best since you could set the cycles at the local level. Would be definitely cheaper than the full controller.

Not something to add here to this integration though - will leave this for you to solve locally! :)
