### ISSUE TITLE
Pool Fountain Not present in HAAS

### ISSUE THREAD

**Issue by MHillyer** [djtimca/haomnilogic#4]
In my Omni App I have a Pool Fountain feature, should be showing in my uploaded telemetry, it is not showing in HAAS. It controls the bubblers.

**Comment by djtimca** [comment]
I can see a relay named Bubblers in your telemetry - would that be it? 

`"Relays":[
               {
                  "systemId":"9",
                  "relayState":"0",
                  "Name":"Bubblers",
                  "Type":"RLY_VALVE_ACTUATOR",
                  "Function":"RLY_WATERFALL",
                  "Alarms":[
                     
                  ]
               }
            ],`

**Comment by djtimca** [comment]
Now looking at what I have saved, I'm not sure I actually have your correct telemetry (also looking at #3). For example I don't even see a spa in the telemetry I've been looking at.

Did you get any errors when you ran the Replit at: https://replit.com/@djtimca/OmniTesting

Any chance you can run it again? You should get no errors, just a prompt to press a key to clear everything.

**Comment by MHillyer** [comment]
Check now? I have run it again. I should have blower for Spa, should have Fountain and Waterfall and Waterslide for Pool.

**Comment by djtimca** [comment]
Still seeing nothing which is weird - no errors on the console page?

**Comment by MHillyer** [comment]
Here's my entry in files after it an:

`[{'systemId': '136445', 'statusVersion': '7', 'airTemp': '103', 'status': '1', 'state': '1', 'configUpdatedTime': '0001-01-01T00:00:00', 'datetime': '2022-06-02T15:46:56.038', 'Relays': [], 'BOWS': [{'systemId': '2', 'flow': '255', 'waterTemp': '-1', 'Name': 'Spa', 'Supports-Spillover': 'no', 'Filter': {'systemId': '12', 'valvePosition': '1', 'filterSpeed': '0', 'filterState': '0', 'lastSpeed': '100', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_SHARED_EQUIPMENT', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '18', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'no', 'Alarms': []}, 'VirtualHeater': {'systemId': '13', 'Current-Set-Point': '95', 'enable': 'no'}, 'Heater': {'systemId': '14', 'heaterState': '0', 'enable': 'yes', 'Shared-Type': 'BOW_SHARED_EQUIPMENT', 'Operation': {'VirtualHeater': {'System-Id': '14', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_2', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_AS_LONG_AS_VALID', 'Shared-Equipment-System-ID': '5', 'Current-Set-Point': '95', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '13'}}, 'Name': 'Heater', 'Alarms': []}, 'CSAD': {'systemId': '0', 'ph': '', 'orp': '', 'status': '0', 'mode': '0', 'Alarms': []}, 'Lights': [], 'Relays': [{'systemId': '15', 'relayState': '0', 'Name': 'Blower', 'Type': 'RLY_HIGH_VOLTAGE_RELAY', 'Function': 'RLY_BLOWER', 'Alarms': []}], 'Pumps': [{'systemId': '6', 'pumpState': '0', 'pumpSpeed': '0', 'lastSpeed': '100', 'Name': 'Cleaner', 'Type': 'PMP_SINGLE_SPEED', 'Function': 'PMP_CLEANER', 'Min-Pump-Speed': '18', 'Max-Pump_Speed': '100', 'Alarms': []}, {'systemId': '7', 'pumpState': '0', 'pumpSpeed': '0', 'lastSpeed': '25', 'Name': 'Waterfall', 'Type': 'PMP_VARIABLE_SPEED_PUMP', 'Function': 'PMP_WATERFALL', 'Min-Pump-Speed': '25', 'Max-Pump_Speed': '100', 'Alarms': []}], 'Heaters': [{'systemId': '14', 'heaterState': '0', 'enable': 'yes', 'Shared-Type': 'BOW_SHARED_EQUIPMENT', 'Operation': {'VirtualHeater': {'System-Id': '14', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_2', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_AS_LONG_AS_VALID', 'Shared-Equipment-System-ID': '5', 'Current-Set-Point': '95', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '13'}}, 'Name': 'Heater', 'Alarms': []}]}, {'systemId': '1', 'flow': '255', 'waterTemp': '88', 'Name': 'Pool', 'Supports-Spillover': 'no', 'Filter': {'systemId': '3', 'valvePosition': '1', 'filterSpeed': '100', 'filterState': '1', 'lastSpeed': '100', 'Name': 'Filter Pump', 'Shared-Type': 'BOW_SHARED_EQUIPMENT', 'Filter-Type': 'FMT_VARIABLE_SPEED_PUMP', 'Max-Pump-Speed': '100', 'Min-Pump-Speed': '18', 'Max-Pump-RPM': '3450', 'Min-Pump-RPM': '600', 'Priming-Enabled': 'no', 'Alarms': []}, 'VirtualHeater': {'systemId': '4', 'Current-Set-Point': '88', 'enable': 'no'}, 'Heater': {'systemId': '5', 'heaterState': '0', 'enable': 'yes', 'Shared-Type': 'BOW_SHARED_EQUIPMENT', 'Operation': {'VirtualHeater': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_2', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_AS_LONG_AS_VALID', 'Shared-Equipment-System-ID': '14', 'Current-Set-Point': '90', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '4'}}, 'Name': 'Heater', 'Alarms': []}, 'CSAD': {'systemId': '0', 'ph': '', 'orp': '', 'status': '0', 'mode': '0', 'Alarms': []}, 'Group': {'systemId': '22', 'groupState': '0'}, 'Lights': [{'systemId': '10', 'lightState': '0', 'currentShow': '12', 'Name': 'Color Lights', 'Type': 'COLOR_LOGIC_UCL', 'V2': 'no', 'Alarms': []}], 'Relays': [{'systemId': '8', 'relayState': '0', 'Name': 'WaterSlide', 'Type': 'RLY_VALVE_ACTUATOR', 'Function': 'RLY_WATER_SLIDE', 'Alarms': []}, {'systemId': '9', 'relayState': '0', 'Name': 'Fountain', 'Type': 'RLY_VALVE_ACTUATOR', 'Function': 'RLY_FOUNTAIN', 'Alarms': []}], 'Pumps': [{'systemId': '6', 'pumpState': '0', 'pumpSpeed': '0', 'lastSpeed': '100', 'Name': 'Cleaner', 'Type': 'PMP_SINGLE_SPEED', 'Function': 'PMP_CLEANER', 'Min-Pump-Speed': '18', 'Max-Pump_Speed': '100', 'Alarms': []}, {'systemId': '7', 'pumpState': '0', 'pumpSpeed': '0', 'lastSpeed': '25', 'Name': 'Waterfall', 'Type': 'PMP_VARIABLE_SPEED_PUMP', 'Function': 'PMP_WATERFALL', 'Min-Pump-Speed': '25', 'Max-Pump_Speed': '100', 'Alarms': []}], 'Heaters': [{'systemId': '5', 'heaterState': '0', 'enable': 'yes', 'Shared-Type': 'BOW_SHARED_EQUIPMENT', 'Operation': {'VirtualHeater': {'System-Id': '5', 'Name': 'Heater', 'Type': 'PET_HEATER', 'Heater-Type': 'HTR_GAS', 'Enabled': 'yes', 'Priority': 'HTR_PRIORITY_2', 'Run-For-Priority': 'HTR_MAINTAINS_PRIORITY_FOR_AS_LONG_AS_VALID', 'Shared-Equipment-System-ID': '14', 'Current-Set-Point': '90', 'Max-Water-Temp': '104', 'Min-Settable-Water-Temp': '65', 'Max-Settable-Water-Temp': '104', 'enable': 'yes', 'systemId': '4'}}, 'Name': 'Heater', 'Alarms': []}]}], 'BackyardName': 'The Taboo Lagoon', 'Msp-Vsp-Speed-Format': 'Percent', 'Msp-Time-Format': '12 Hour Format', 'Units': 'Standard', 'Msp-Chlor-Display': 'Salt', 'Msp-Language': 'English', 'Unit-of-Measurement': 'Standard', 'Alarms': [], 'Unit-of-Temperature': 'UNITS_FAHRENHEIT'}]`

Spa is showing in the BOWS array right near the top.

**Comment by djtimca** [comment]
Update 1.0.2 should hopefully solve this. Please report back (unfortunately I don't have any relays in my pool to be able to test).

**Comment by djtimca** [comment]
Excellent thanks. I think I need to do a better job with some of the icons, but can sort that in a future release.

I should be able to look at the duplication Monday for the other issue.
