### ISSUE TITLE
No Entity to report Average Salt level

### ISSUE THREAD

**Issue by MHillyer** [djtimca/haomnilogic#41]
Hey there, looking through my app and I'm seeing that there's a diagnostic for instant salt, that is showing in the integration as pool_chlorinator_salt_level, but there's no corresponding entity for Average Salt. I'd rather alert off of average salt because the value is continuously available, while Instant Salt is only available while the system is actively chlorinating.

PS: Any updates on local connectivity?

**Comment by djtimca** [comment]
I believe this was added already. Local integration is available through another developer.
