### ISSUE TITLE
HA 2023.3 throwing errors with Omnilogic integration

### ISSUE THREAD

**Issue by knwpsk** [djtimca/haomnilogic#46]
Error fetching Omnilogic data: Error updating from OmniLogic: Error converting Hayward data to JSON.
5:40:18 AM – (ERROR) Omnilogic (custom integration)
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for omnilogic using this method at custom_components/omnilogic/__init__.py, line 62: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
February 11, 2023 at 11:36:34 AM – (WARNING) helpers/frame.py

**Comment by djtimca** [comment]
I believe this is already fixed.
