### ISSUE TITLE
Omnilogic integration failing to load since HA update to 2023.5

### ISSUE THREAD

**Issue by knwpsk** [djtimca/haomnilogic#49]
This integration is failing to load. 
Started a few days ago after HA update to 2023.5 (I think). 

From logs:

Logger: homeassistant.config_entries
Source: custom_components/omnilogic/__init__.py:62
Integration: Omnilogic ([documentation](https://github.com/djtimca/haomnilogic), [issues](https://github.com/djtimca/haomnilogic/issues))
First occurred: May 10, 2023 at 7:57:48 PM (2 occurrences)
Last logged: 2:26:52 PM

Error setting up entry Pool_Controller for omnilogic
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/omnilogic/__init__.py", line 62, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by knwpsk** [comment]
Reloading the integration does not help.
I haven't messed with it in any way. :)

**Comment by matthewaaronthacker** [comment]
If you go to HACS there should be an update available that fixes the issue. (at least it did for me)

**Comment by knwpsk** [comment]
@matthewaaronthacker yes that resolved it! Thanks for pointing it out.
(Now I'm creating an alert to tell me or show me on dashboard when HACS updates are available!)
