### ISSUE TITLE
Dumb question - Is this already available in HACS?

### ISSUE THREAD

**Issue by mikesalz** [djtimca/haomnilogic#5]
I am probably doing something wrong.  But I can't find OmniLogic in HACS.

I get this when I hit Explore & Download Repositories:

![image](https://user-images.githubusercontent.com/46855061/171679383-d63f9ada-4f75-4a5c-b6d5-9026f18392ae.png)

And I get this when I try to add the custom repository:

![image](https://user-images.githubusercontent.com/46855061/171679482-872e0f48-8aba-4f6e-a023-e11db1984b1f.png)

**Comment by djtimca** [comment]
It is not published to HACS yet sorry - add https://github.com/djtimca/haomnilogic as a custom repository. Not sure why you are getting the message about it existing, I can confirm it is not in the latest release there. (The only thing I can think of is you may have already successfully added it).

**Comment by mikesalz** [comment]
Hey @djtimca!  Sorry to be such a pain in the butt.  I saw you updated the hacs.json file.  So I removed the integration and deleted my omnilogic folder, then restarted HA.  But I am still seeing CA in the hacs.repositories file.  I even manually removed the omnilogic entry from the file and then search again.  I think this file is updated each time you to a search because CA came right back.  And I'm still getting that "Repository 'djtimca/haomnilogic' exists in the store." message when I try to add the custom repository in HACS.

Any chance CA wasn't actually removed in hacs.json?  Or maybe can you explicitly add US too?  Any other ideas?

![image](https://user-images.githubusercontent.com/46855061/172639314-038c51e4-8d66-4f9d-92ed-cef7c310f229.png)

**Comment by djtimca** [comment]
I can confirm in the repo that it is removed:
![image](https://user-images.githubusercontent.com/60706061/172642816-bb703e47-d5fd-4e90-b15e-f59b6f1d8d4a.png)

I also downloaded the Zip file from release 1.0.7 and can confirm that it is not in the hacs.json file there either.

**Comment by mikesalz** [comment]
So weird.  I see that in the hacs.json file in 1.0.7 as well.  Maybe it takes some time to propagate through HACS?  I don't know.  I guess I'll wait a few days and give it another try.  I can still manually download the zip and move it into my custom_components folder.  But it sure would be nice if I could update through HACS!

**Comment by djtimca** [comment]
Unless I can convince the home assistant guys to remove the built-in integration, I can't add it to the default store unfortunately.

**Comment by mikesalz** [comment]
I think you'd have better luck convincing the sun to not rise in the east.  OK, I will just keep doing what I'm doing.  At the end of the day, I'm just happy to see improvements being made in this integration.  If I have to manually update it, it's not a huge deal.  Thanks!

**Comment by mikesalz** [comment]
I finally figured it out!

I submitted a HACS issue and was given this response:

> If it says that, then you have it already.
> 
> It can be you have set a country limitation in your HACS configuration, if that is the case remove that configuration, or leave HA running for 48h (no restarts).

And this:

> once downloaded the cached data is overwritten by new which removed that key.
> (Same would also happen after HA has been running for 48h as that is when it fetches data for non-downloaded repositories)

I wasn't even aware of a country limitation in my config.  I found that and changed it, and was able to download the repository.  Also, that explains why I still saw CA.  I guess it takes 48 hours to refresh.

Anyway, thanks again for all of your help!  Have a great weekend!
