### ISSUE TITLE
Freeze Protect status

### ISSUE THREAD

**Issue by soupman98** [djtimca/haomnilogic#56]
I just managed to get this added to my Raspberry Pi 4 running HA. Thanks so much.

Some things I don't yet see
Heater status -> on/off
Chlorinator status -> on/off
Freeze Protect mode status (main pump) -> on/off 
Freeze Protect mode status (water features) -> on/off 
Freeze protect settings (what temp does it kick on)?

Glad to help test or even play with coding.. noob in the space though

**Comment by djtimca** [comment]
I don't have Chlorinator done yet - that's already an open issue request #44.

Heater is managed through modes - have a look at the services available in the documentation.

I do not see anything related to "Freeze Protect" in the API documentation unfortunately. Not sure what it does as I don't have that on my pool. When it gets cold we close it here in Canada :)

**Comment by soupman98** [comment]
I see in the 3rd party HACS integration a couple of alarms.. (Pump, Chlorinator, I'm wondering if that might be freeze protect status.
So here's the skinny on freeze protect...
You enable it in the Hayward controller and set a temperature. You have to enable it on your body of water (main pump) and water features.
In my case i have 1 bubbler (and an associated powered valve) and 3 deck jets (and an associated powered valve).
You also set the freeze protect RPMS for the pump (not sure about complex setups with multiple pumps for spas and water falls , I just have one VSP.

When the air temp sensor reads below the freeze protect value, it starts the pump, sets it to speed, moved the valves to necessary position.
From what I understand others.. the Omnipool may turn water features on an off because of how spas spill to pools and such.

When it's in Freeze Protect mode - the screen indicates that. I can manually override the pump speed to higher than but not lower than the FP speed.

I have an old MSP dump from my Omnipool, but can't recall how to pull a new one.. I forget if it's via the web browser to H/OP.

[What Happens While An Omni Is In Freeze Protect]

There are alarms for backyard lights (relays) and pool lights (odd) but alarms for freeze status makes sense to me for bubbler, heater, jets, and pump (makes sense if F/Protect)
[cid:65230464-c50c-4ab2-9bfe-90c987de6290]
________________________________
