### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by sddgit** [djtimca/haomnilogic#8]
Sorry to raise an issue when there’s not really anything to report, but I’d like to find out the best way to get hold of the documentation for the Hayward API, both cloud and local. I understand they only supply it under NDA. What’s the best way to approach them to get hold of it?

**Comment by djtimca** [comment]
I'm not sure who is now the primary contact at Hayward - I haven't had to interact with them for a couple years.

I recommend trying to contact them using one of the methods outlined at: https://www.hayward-pool.com/shop/en/pools/contact-hayward

**Comment by sddgit** [comment]
Thank you very much for the reply. I’ll see how I go…
